ietf-tapswg/api-drafts

draft-trammell-taps-interface.md

Add text for Specific Protocol Properties

---

draft-brunstrom-taps-impl.md
draft-pauly-taps-arch.md
draft-trammell-taps-interface.md

Fixes all outstanding London API issues except #92 and #93

Brian's Monday editorial pass on API

---

draft-trammell-taps-interface.md

Note implications of constant rate capcity profile

---

draft-trammell-taps-interface.md

Clarify upper bound on message size

---

draft-trammell-taps-interface.md

made notation more uniform (mostly capitalization)

---

draft-ietf-taps-interface.md

Add text for Final Messages to support half-close

---

draft-ietf-taps-interface.md

Rework text for interface types

---

draft-ietf-taps-interface.md

fixes #158, and addresses #186

Congestion control and Gorry's read-through comments

---

draft-ietf-taps-interface.md

And add an early data metadata value.

Split Message receive Metadata into a separate section

---

draft-ietf-taps-interface.md

Suggestion to address #155 and #157 in the API doc.

API events

---

draft-ietf-taps-interface.md

as I started reviewing issues in advance of the interim, I saw that #102 was already mostly fixed, but I made a few editorial changes to the language there.

fix #102, some changes to Resolve() language

---

draft-ietf-taps-interface.md

The point of this is to draw a line to minset, to make sure we're not missing something. Names of properties in the current document may be wrong, and I can fix them after the current round of updates by @britram - but this is more about what's missing than what's there.
I'm happy to report that very, very little is missing!

A minset appendix

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Not many text fixes needed - quite a bit of text reflected the old choice of Priority anyway and wasn't correctly updated for Niceness   :-)

Change Niceness to Priority, as agreed with @britram. Closes #228

---

draft-ietf-taps-interface.md

Added a "Default" preferece level for Selection Properties

---

draft-ietf-taps-interface.md

Note that Idempotent is needed for UDP like protocols

---

draft-ietf-taps-interface.md

This adds an explicit Listener object to the API (closes #301) to
- clarify behaviour of multi-streaming protocols (closes #269)
- clarify behaviour and enable re-use of Preconnections (closes #222)

Added Listener object to the API

---

draft-ietf-taps-interface.md

Closes #319, #318. Partially addresses #315.

Some defaults and editorial fixes

---

draft-ietf-taps-arch.md

Rename "Basic Objects" to "Connection Objects" to reduce confusion

---

draft-ietf-taps-arch.md

Cleanup diagram to remove message, and add rendezvous

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Allow for error events to include an optional reason

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Move Message Framer implementation details to implementation

---

draft-ietf-taps-interface.md

Address privacy property, #300

---

draft-ietf-taps-interface.md

Add multipath property enumeration

---

draft-ietf-taps-arch.md

Add text for server-side "racing"

---

draft-ietf-taps-arch.md

Note that Security Considerations and Acknowledgments changes are newline-rewrap only.

Minor editorial tweaks to Architecture

---

draft-ietf-taps-arch.md

A complete arch. read-through, leading to a couple of nit fixes and other minor suggestions

Mw arch read through

---

draft-ietf-taps-arch.md

Explain half-close vs close()

---

draft-ietf-taps-arch.md

Generalise the discussion of Rendezvous in arch.
Closes #396

Update description of rendezvous

---

draft-ietf-taps-impl.md

Add some details to framers

---

draft-ietf-taps-arch.md

"within a message" twice in the same sentence

nit - "within a message" twice

---

draft-ietf-taps-interface.md

I guess we could actually remove all commas in this sentence but previously there were definitely too many...

Too many commas

---

draft-ietf-taps-interface.md

I read the API draft and fixed a couple of minor issues. That is, they're minor as far as I can see - please tell me if you disagree.

API draft: Minor fixes

---

draft-ietf-taps-interface.md

s/messages can be sent/messages can be sent and received/

minor edit to sec 4

---

draft-ietf-taps-interface.md

Indicate use of streams for unordered messages as example

---

draft-ietf-taps-arch.md

Proposed some text for #470 - I think this summarizes the "flexibility" advantage of TAPS that we elaborate on in Section 2.3.

Clarify "adopt", summarize sec 2.3

---

draft-ietf-taps-arch.md

Be more consistent in naming Transport Services

---

draft-ietf-taps-interface.md

These are all my self-assigned issues, where I think the discussion has converged.
Closes #404, #426, #434, #438, #441, #443, #451, #462, #467

Various API fixes

---

draft-ietf-taps-arch.md

Add security parameters to arch

---

draft-ietf-taps-impl.md

I think this is just an minor oversight that needs fixing but I would like someone to double-check before merged...

Adjust level of branching related subsections

---

draft-ietf-taps-impl.md

Mainly adding references to arch and API docs...

preamble text in security considerations section

---

draft-ietf-taps-impl.md

Text around "PRIMITIVENAME" in implementation draft (issue #549)

---

draft-ietf-taps-interface.md

Connection state diagram

---

draft-ietf-taps-arch.md

Architecture NiT: /assumes/

---

draft-ietf-taps-interface.md

Resolving Editorial NiTs in section 1 #569

NiTs in section 1

---

draft-ietf-taps-impl.md

Address editorial comments on Implementation

---

draft-ietf-taps-impl.md

Not intended to change meaning, but intended to improve reading, see issue #576.

Rewording of Section 4.1.5 on Properties

---

draft-ietf-taps-interface.md

Remove specification that message is bytes-like

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

.. that gets in the way of using streams when cloning.
Closes #441.

Added a selection property for a special communication pattern

---

draft-ietf-taps-impl.md

Clarify immediate racing

---

draft-ietf-taps-interface.md

Correlate send/receive events with calls

---

draft-ietf-taps-interface.md

Make batch example more clear

---

draft-ietf-taps-interface.md

Closes #437.
* allow to control active/passive opertaion
* clairify functionality
* allow to control exposure of alternative addresses

Update Multipath properties - closes #437

---

draft-ietf-taps-impl.md

adjusted text according to #531

---

draft-ietf-taps-impl.md

Impl: update batch send text

---

draft-ietf-taps-impl.md

Use "Simultaneous" and "Staggered"

---

draft-ietf-taps-interface.md

Update multipath interactive definition

---

draft-ietf-taps-interface.md

Add diagram and more explanation for message framers in API doc

---

draft-ietf-taps-impl.md

Keep Minset protocol mappings, create template for new mappings

---

draft-ietf-taps-interface.md
recvChecksumLen

This contains a mix of normalising editorial work, corrections to text and other issues.

Set of updates to API

---

draft-ietf-taps-interface.md

remove requirement for enumeration of enumerations

---

draft-ietf-taps-interface.md

Fix figure legends in API

---

draft-ietf-taps-interface.md

Clarify behaviour of Rendezvous()

---

draft-ietf-taps-interface.md

addresses #630 
However, we now have this path change event but it seems we actually don't have an interface to the access the path object to figure out what exactly changed...?

Path Change event added

---

draft-ietf-taps-interface.md

Feel free to cherry-pick. Some of these are self-explanatory; in other cases, I'll add a comment to explain the change.

Various nits and wordsmithing

---

draft-ietf-taps-interface.md

Add a Group Connection Limit, extend Client example with clone.

---

draft-ietf-taps-interface.md

caveats on temporary local addresses

---

draft-ietf-taps-interface.md

fixes #619 
(well, the priority framework is still confusing, this PR makes it clear that that is intentional, and why)

Clarify priority framework

---

draft-ietf-taps-interface.md

Clarifying example for partial receives. Closes #669.

---

draft-ietf-taps-interface.md

Remove "excessive retransmissions". Closes #677.

---

draft-ietf-taps-interface.md

move text on early name binding to privacy consideration

---

draft-ietf-taps-interface.md

Add new sections on keep alives

---

draft-ietf-taps-interface.md

Clarifying text on Framers

---

draft-ietf-taps-interface.md

Remove vestigial reply concept from Post Sockets

---

draft-ietf-taps-interface.md

Add pseudocode example for security cache management

---

draft-ietf-taps-interface.md

Allow multiple Local and Remote Endpoints on Preconnection

---

draft-ietf-taps-interface.md

Update Rendezvous() description

---

draft-ietf-taps-interface.md

Update Rendezvous() examples

---

draft-ietf-taps-impl.md

These are mostly wording changes for clarification. Feel free to cherry pick.

2020-12-10 krose review suggested changes

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Transport system -> Transport Services system

---

draft-ietf-taps-impl.md

Describe framer passthrough mode

---

draft-ietf-taps-interface.md

This is probably not done, but it's getting closer to separating the abstract API from concrete API details. Edits, comments, and criticism are welcome, of course.

Improve API abstraction #658

---

draft-ietf-taps-impl.md

My first try to make a PR from the web interface. Maybe this compiles without problems?
Resolves #703.

Fix "confirmed route". Resolves #703

---

draft-ietf-taps-impl.md

Clarify what it means to not connect

---

draft-ietf-taps-impl.md

Change Unconnected to Connectionless

---

draft-ietf-taps-interface.md

Add CloseGroup

---

draft-ietf-taps-interface.md

I did a check of the minset appendix to see if anything should be updated, as some property names etc. could have changed.
I wrongly expected a small PR to only be "editorial" before, but this time I'm really sure   :-)

Small updates to the minset appendix for consistency

---

draft-ietf-taps-interface.md

add Closing to the state diagram

---

draft-ietf-taps-impl.md

Now I feel like I'm shaving the yak. This is more than what we talked about in the interim, but it felt like the following sentence required additional clarity. Let me know if I misunderstood the intended meaning, in which case I will rephrase.

Packet vs. datagram

---

draft-ietf-taps-impl.md

Editorial rollup, bis.

---

draft-ietf-taps-interface.md

Update to fix NITS in draft-ietf-taps-interface.md

---

draft-ietf-taps-interface.md

While reviewing for last call, I didn't find the abstract very strong. Given I'm an authors, I thought I make another proposal, however, really just that - a proposal...

Proposed editorial changes to abstract and intro

---

draft-ietf-taps-impl.md

Addition to clarify what happens when a transport system replays messages - #780

PR for when a transport system replays messages

---

draft-ietf-taps-interface.md

Remove one confusing sentence (#790)

---

draft-ietf-taps-interface.md

Remove the mention of "hierarchy" in priority text

---

draft-ietf-taps-arch.md

Fix Case of Loc/Remote

---

draft-ietf-taps-interface.md

I was so confused, if people like this PR I think I might be less confused in future.

Unconfuse checksum for gorry

---

draft-ietf-taps-impl.md

Trying to address use of “remote” and "local"  #755

Local/Remote in Impl

---

draft-ietf-taps-interface.md

Local/Remote Endpoints

---

draft-ietf-taps-interface.md

Make disabling security explicit

---

draft-ietf-taps-interface.md

Add appendix note about object freeing

---

draft-ietf-taps-interface.md

Explicitly distinguish Callbacks from Events

---

draft-ietf-taps-interface.md

This tries to write something small but specific about Network Policies #701

Trying to add some policy to the path selection

---

draft-ietf-taps-interface.md

Hopefully clearer text for the ReceiveError Event.

---

draft-ietf-taps-interface.md

(Gracefully,  he he  :)  ) Closes #761.

Clarify Events upon various close / abort calls.

---

draft-ietf-taps-interface.md

Update and explain choices
Seeks to address #821

Change B.2.3. unreliable-datagram profile

---

draft-ietf-taps-impl.md

This is a first cut, I'll update next.

PR to align Capacity profile with API

---

draft-ietf-taps-interface.md

Fixes #812

---

draft-ietf-taps-interface.md

Closes #859
This is quite minimal... meant as a start. Or is this already enough?

Preconnections are just structs

---

draft-ietf-taps-interface.md

fix #798, fix #799, fix #802, fix #803, fix #805, fix #807, fix #811, fix #813, fix #814, fix #816, fix #817.
More to follow in a subsequent PR (it's lunchtime. :) )

Many editorial fixes (rollup 1)

---

draft-ietf-taps-interface.md

fix #819. fix #820. fix #843. fix #850. fix #854.

More editorial fixes.

---

draft-ietf-taps-interface.md

section refactor

---

draft-ietf-taps-interface.md

editorial rollup number three

---

draft-ietf-taps-interface.md

Clarify Setting Message Properties on Preconnections and Connections

---

draft-ietf-taps-interface.md

Remove obsolete example from §9.3.2.1

---

draft-ietf-taps-impl.md

Remove Karl-Johan Grinnemo from authors.

Author cleanup

---

draft-ietf-taps-interface.md

Add a ReceivedPartial example

---

draft-ietf-taps-interface.md

Resolves #899, #902, #903, #904, #906, #907, #916.

A few simple editorial fixes from the ART-ART review.

---

draft-ietf-taps-interface.md

Remove a paragraph because it doesn't fit and doesn't add value.

---

draft-ietf-taps-interface.md

Change first appearance of "cloning" and add forward reference.

---

draft-ietf-taps-interface.md

Resolves #905.
Note that this PR does not say *only* the following characters are allowed... it just lists some that *are* allowed.

Be more specific than "alphanumeric"

---

draft-ietf-taps-interface.md

Be firm, but avoid MUST NOT apply across different protocols
TO ADDRESS #914

Remove a MUST NOT

---

draft-ietf-taps-arch.md

Addressed MW comments; and also tidied several successive similar examples into one para.

Arch tidy of mix concerns

---

draft-ietf-taps-interface.md

Resolves #896. Resolves #897.
This replacement for PR #930 was discussed at the last interim.

Special values and update definition of "numeric"; replaces #930.

---

draft-ietf-taps-impl.md

Clarify Pooled Connections vs. Connection Groups. Resolves #956.

---

draft-ietf-taps-interface.md

Be explicit about objects being treated as call-by-value

---

draft-ietf-taps-interface.md

Add a reference to AddRemote

---

draft-ietf-taps-interface.md

Tweaking SecurityParameters example

---

draft-ietf-taps-interface.md

Rename connPrio -> connPriority

---

draft-ietf-taps-interface.md

Renamed msgPrio -> msgPriority

---

draft-ietf-taps-interface.md

Adding '(non-negative)' to connPriority Type line

---

draft-ietf-taps-interface.md

Rename tcp.userTimeout -> tcp.userTimeoutEnabled

---

draft-ietf-taps-interface.md

Rename tcp.userTimeoutRecv -> tcp.userTimeoutChangeable

---

draft-ietf-taps-interface.md

connCapacityProfile Type and Default

---

draft-ietf-taps-interface.md

s8.1.11.2/.3/.4 size in bytes

---

draft-ietf-taps-interface.md

Updating outdated references

---

draft-ietf-taps-impl.md

Mention framer synchronization

---

draft-ietf-taps-impl.md

Explain application preferences for addresses

---

draft-ietf-taps-interface.md

Message Property default value inheritance

---

draft-ietf-taps-interface.md

Reference RFC 5280

---

draft-ietf-taps-impl.md

Clarify leaf node establishment

---

draft-ietf-taps-impl.md

Editorial changes: Protocol Stack and Protocol Instance

---

draft-ietf-taps-impl.md

Soften order of operations text

---

draft-ietf-taps-impl.md

Incorporate Kyle's suggestions

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Closes #1040. Closes #1046.
I also fixed some capitalization errors in passing.

Fixing property names and their references

---

draft-ietf-taps-interface.md

Add language pointing out risks of 0RTT session establishment

---

draft-ietf-taps-impl.md

Remove mention of ICMP errors for multicast receive

---

draft-ietf-taps-impl.md

Add notation reference for framers

---

draft-ietf-taps-impl.md

Align framer parameter names with API

---

draft-ietf-taps-impl.md

Introduce racing more clearly

---

draft-ietf-taps-impl.md

Describe metadata-only messages

---

draft-ietf-taps-interface.md

Reference v6 address considerations for temp local property

---

draft-ietf-taps-impl.md

Updates text for MPTCP.

---

draft-ietf-taps-impl.md

Takes care of item 5 and closes #608 .

Make mentions of Closed Event consistent

---

draft-ietf-taps-arch.md

Mention future minset additions

---

draft-ietf-taps-arch.md

Clarify protocol stack equivalence

---

draft-ietf-taps-impl.md

Add ranking criteria for protocol options

---

draft-ietf-taps-arch.md

/transport/ should be /connection state/

Connection state is torn down

---

draft-ietf-taps-arch.md

Previous agreed text will be added to this PR.

Take 2 at Glossary and terms PR

---

draft-ietf-taps-arch.md

Responding to review and tighter wording for the Arch draft:  Undefined "transport object" #1084

/transport object/Connection/

---

draft-ietf-taps-arch.md

Add explanation for the connection lifetime diagram

---

draft-ietf-taps-arch.md

Add another reference to 3.3

---

draft-ietf-taps-arch.md

Feel free to approve or propose changes to improve this sentence in Arch.

An attempt to craft a sentence for Issue #1124

---

draft-ietf-taps-interface.md

There's four of them right so it's "... these properties ..."

Another nit

---

draft-ietf-taps-impl.md

Send failures

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Connection termination update

---

draft-ietf-taps-impl.md

Intro update: clarify normative status. Closes #1133

---

draft-ietf-taps-impl.md

Note that the architecture forbids downgrade

---

draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Closes #1141.
This is a bit different than we discussed - see my longer comment in #1141.

MUXed listeners

---

draft-ietf-taps-impl.md

Nits for tree/racing descriptions

---

draft-ietf-taps-impl.md

Improve introduction of message framers

---

draft-ietf-taps-impl.md

Fix DNS nits

---

draft-ietf-taps-interface.md

Fix peer example

---

draft-ietf-taps-interface.md

Clarify behaviour of multicast

---

draft-ietf-taps-interface.md

Downgrade (most) normative references

---

draft-ietf-taps-interface.md

Make implementation freedom clearer

---

draft-ietf-taps-interface.md

Closes #1188 
Attempt at closing the issue, based on my interpretation. Happy to have a different direction too.

Clarify multiple remote endpoints

---

draft-ietf-taps-interface.md

Minor wording change in example in section 3.1.2.

---

draft-ietf-taps-interface.md

Add certificates and clean up callbacks from GenArt review.
fix #1184

Security parameters fixes

---

draft-ietf-taps-interface.md

Added basic types: string, IPv4 address, IPv6 address.

---

draft-ietf-taps-arch.md

Includes:
Properties allowed for use of DNSSEC or DoH? #1224 Some items in section 2 #1217 (adding the word DNS, ref to figure 1,2)

More on Equivalence

---

draft-ietf-taps-arch.md

A tiny fix to one sentence

---

draft-ietf-taps-interface.md

IPv6 scoping fixes

---

draft-ietf-taps-arch.md

One Receive Event per Receive call

---

draft-ietf-taps-impl.md

This includes: CONNECT.UDP-lite; LISTEN.UDP-Lite; SEND.UDP-Lite; RECEIVE.UDP-Lite; ABORT.UDP-Lite; ERROR.UDP-Lite; SET_DSCP.UDP-Lite; SET_DF.UDP-Lite; SET_ECN.UDP-Lite; GET_ECN.UDP-Lite.

Fix UDP(-Lite)

---

draft-ietf-taps-arch.md

No more "transport networking"

---

draft-ietf-taps-interface.md

Replace without corruption

---

draft-ietf-taps-interface.md

Generic Properties

---

draft-ietf-taps-arch.md
draft-ietf-taps-impl.md
draft-ietf-taps-interface.md

Remove the use of "native"

---

draft-ietf-taps-interface.md

Rework datagram in example

---

draft-ietf-taps-interface.md

Fix word rendezvousing and purposes in API

---

draft-ietf-taps-interface.md

Non-Preference Selection Properties don't change their type

---

draft-ietf-taps-interface.md

Please consider these proposed changes

Review of "should" in API

---

draft-ietf-taps-interface.md

Create IANA registry for Tansport Property Namespace 

---

draft-ietf-taps-interface.md

Explain errors for message properties

---

draft-ietf-taps-interface.md

Hostnames SHOULD be FQDNs

---

draft-ietf-taps-interface.md

Closes #1364 
All hail the camel.
Trivia: "Behind my camel" is a great song by The Police.

HostName not Hostname

---

draft-ietf-taps-interface.md

Prioritization: don't talk about "performance"

---

draft-ietf-taps-interface.md

Elaborate on preconnection reuse

---

draft-ietf-taps-impl.md

Rephrase batch sending

---

draft-ietf-taps-interface.md

Clarify rate bounds

---

draft-ietf-taps-interface.md

Reference RFC 5952

---

draft-ietf-taps-interface.md

Opportunistic security is unauthenticated

---

draft-ietf-taps-interface.md

Clarify PvD identification

---

draft-ietf-taps-interface.md

Update multicast example address

---

draft-ietf-taps-interface.md

Add ephemeral port example

---

draft-ietf-taps-impl.md

Point at Software Heritage Archive

---

draft-ietf-taps-interface.md

fixes #1286.
fixes #1359.
fixes #1375.
fixes #1389.
fixes #1358 as a side-effect.
fixes #1367 as a side-effect.
fixes #1370 as a side-effect.

Disambiguate security properties per rdd review

---

draft-ietf-taps-arch.md

Security equivalence is in system policy.

---

draft-ietf-taps-interface.md

Three new read-only Connection properties

---

draft-ietf-taps-interface.md

How to choose security protocols is out of scope, but cite RFC 8922

---

draft-ietf-taps-interface.md

Well-known service names come from the IANA list

---

draft-ietf-taps-interface.md

Interfaces -> network paths

---

draft-ietf-taps-interface.md

Rework aliases

---

draft-ietf-taps-interface.md

useTemporaryLocalAddress should be Prefer for Rendezvous

---

draft-ietf-taps-interface.md

Clarify Rendezvous behaviour and who's in charge of ICE

---

draft-ietf-taps-interface.md

see https://mailarchive.ietf.org/arch/msg/taps/1or3_qkM3GeJM2rYBOj3IvxbO1E/

s/SHOULD/MUST, addressing a DISCUSS item from Lars Eggert

---

draft-ietf-taps-interface.md

Clarify status of security parameters
