draft-pauly-taps-arch.md
Option for addressing #79: replace Content in the architecture with Message (where appropriate); use more general concepts like data in the background/design explanation, use Message in the concepts section, and refer to a Message's content when we need to talk about the bytes specifically in this Message.
=> Replace Content with Message

draft-brunstrom-taps-impl.md, draft-trammell-taps-interface.md
The previous text didn't support sending multiple messages across vanilla TCP without framers/deframers or a top-level protocol in the stack that would de-frame. This change allows sending multiple messages across vanilla TCP and handing them over as bytes to an application that, by itself, detects message boundaries from the chunks of bytes that it gets.
=> Fixes to sending and receiving messages to support vanilla TCP

draft-pauly-taps-arch.md
This is a reworking of the text from Section 4.2 of draft-trammell-taps-post-sockets-03, intended to help motivate the choice of Message-based APIs with framing for the transport services architecture. The level of detail here seems appropriate for the architecture document, rather than the API.
=> Add text about framing

draft-trammell-taps-interface.md
Send parameters were subsections, transport selection properties were not. This fixes that by promiting transport selection properties to subsections, and reorganizing the sections slightly to make that fit.
There are no changes to technical content in this PR.
=> make transport selection properties subsections, too

draft-trammell-taps-interface.md
Removes Immediate Acknowledgment and makes it an optional implicit feature of Low Latency profile, renames Instantaneous Capacity Profile to Transmission Profile. Addresses #90; we should open a new issue to discuss whether we want to split Capacity Profile back out.
=> coalesce immediate acknowledgment into low latency profile

draft-brunstrom-taps-impl.md, draft-trammell-taps-interface.md
Added text about what happens when an application specifies both protocol and path selection properties. Path selection properties have precedence. I added examples to both API and implementation draft to illustrate this. Relates to #149
=> Conflicting policies

draft-trammell-taps-interface.md
This commit fixes bug #165 by making transport parameter types explicit.
It also fixes  Path- and Protocol Selection Properties from "binary + preference" to preferences type.
With the old boolean properties, one could do things like "prohibit Reliable Transport false" - is that the same as "prefer Reliable Transport true"?
=> Transport Parameter Fixes for -00

draft-ietf-taps-arch.md
Integrate Gorry's comments from #187 
This does not yet address Gorry's two other issues, which cover the background section, or potentially moving the transport implementation earlier in the document.
=> Address architecture nits

draft-ietf-taps-arch.md
Satisfies #172, including text for both generic protocol equivalence and security protocols.
We may want to move the section around organizationally later, as per some of Gorry's comments on structure. However, I reference terms from our concept definitions, so it is easier to write in the latter portion of the document.
=> Add architecture text for protocol equivalence

draft-ietf-taps-interface.md
Satisfies #148 
- Support partial sends more naturally by splitting out into Message, messageData, and endOfMessage flag.
- Do the same for Receive
- Receive should also take minIncompleteLength to specify how partial receives are treated (or not, by default)
=> Rework partial sends and receives

draft-ietf-taps-interface.md
This is my attempt to address #112 with something that's (IMO) less clunky in the common case than #124. 
I'm not a big fan of this way of doing things either -- specifically, I think the semantics of RendezvousAndSend(), while consistent, are probably wrong.
=> InitiateAndSend() / RendezvousAndSend()

draft-ietf-taps-interface.md
1 tiny fix suggested to make the text a little clearer (because the default "complete message" delivery may need a de-framer, or the whole Connection may function as a message), and pointed at a possible error when delivering partial data (it's already written elsewhere, but the suggestion makes a sentence more correct, I believe).
=> Small changes to "receive"

draft-ietf-taps-interface.md
Rather than saying "this can only be queried" everywhere, I split this into setting and querying now, and I also moved SoftErrors in there. It's not precisely "querying" for a Property, but it's the closest match - better than "Connection Termination", I think (this is where SoftErrors were before).
=> Set/query conn. properties (sec 9) structure change

draft-ietf-taps-interface.md
I gave the document a very careful back-to-back read. My take-away was that removing the Message Context Parameters from where they are, and just pointing to a later section, would make for a bad reading experience. Basically, it would feel like an empty shell - at some point, the reader wants to see something tangible, and so, reading all these Message properties where they appear is satisfying, in a way. The document would get quite tough to digest if it would just provide the "framework" for sending, receiving etc., and we have to wait for the "meat" until the end, where it is then offered in a very organized fashion.
Hence, I decided to leave all the message properties described where they are (as Message Context Parameters). That was my approach to de-duplication in this PR.
Side …
=> Transport Property clean-up after the re-org. De-duplication etc.

draft-ietf-taps-interface.md
- de-duplicates some properties in 7.3. and 12
- moves up some message properties missing in 7.3.
- make type definition consistent across all properties
This ignores Classification and Applicability labels which are subject
to removal in another PR moving Selection and Connections properties up.
Section 12.3 will most likely be replaces with a table then.
=> This fixes inconcistencies from PR #217 - Message Properties move to Section 7.3

draft-ietf-taps-interface.md
I didn't like something about reliability (let's not throw an error when we can't be UNreliable, only when we can't be reliable). I updated the text on ordering a bit, to say that the Property is ignored for the first Message on a Connection, and rephrased it slightly to talk about the receiver-side transport system and the receiving application - before, the text might have talked about a sender-side behavior.  I added a TODO DISCUSS comment about per-message Niceness.
=> Some clarifications in property text

draft-ietf-taps-interface.md
This is the second step towards applying our new Properties
Classification. It moves up the Connection Properties and annotates most
places with stuff to do.
=> Moved Connection Properties up to #introspection

draft-ietf-taps-interface.md
This is a (work in progress) attempt to clean up Capacity Profile as a selection property along the lines of the state of the discussion in #142.
@gorryfair: you had a suggestion to add "High Throughput Data" as a separate profile mapping to AF2n, but I don't know anything else about what this would actually imply for transport selection; can you help me out here?
=> clean up capacity profile per #142

draft-ietf-taps-interface.md
Alternate fix for fragmentation/segmentation prohibited in a single message property, per discussion.
Merge only one of these. :)
=> singular transmission fix for #226

draft-ietf-taps-interface.md
Message Context Parameters/Properties are now Message Properties, and associated terminology cleanup. Addresses part of the resolution to #218.
=> Message Properties terminology cleanup

draft-ietf-taps-arch.md
I guess here is not nessecarily a notification required in sychronuous communication
=> small wording edit on event driven API

draft-ietf-taps-interface.md
This does the following things with the properties from the appendix, based on https://datatracker.ietf.org/meeting/103/materials/minutes-103-taps-00.html
- direction of communication: moved to the main text
- "Suggest a timeout to the Remote Endpoint": moved to the main text but explicitly described as a TCP-specific property; also changed it to contain all the parameters that UTO really has
- traffic category: removed. Mirja said "Let's see if there's anything in the implementation document that actually needs this information" but I figured that chances are low, and if this really happens we can still re-introduce this later.
- size to be sent or received: removed
- duration: removed
- send or receive bit-rate: changed this to specify an upper and/or lower bound
- cost preferences: …
=> IETF 103 discussion results. Closes #37

draft-ietf-taps-interface.md
Notable changes:
- added control over using multipath (which was a late addition to minset)
- added a timeout for conn. establishment, separate from the other conn. abort timeout (see #109)
- renamed InitiateWithIdempotentSend into InitiateWithSend, and adjusted the text to recommend declaring idempotence. This addresses the minset function that goes back to TCP's send-with-SYN.
=> Last missing bits from minset. Closes #109. Closes #246.

draft-ietf-taps-arch.md
- fixes Properties Terminology and aligns them to the API 
- adds Properties as "Basic Object"
- updates Figure 2
=> Re-align Properties in Architecture - closes Issue #256

draft-ietf-taps-interface.md
This closes #230 and addresses a comment about soft errors by @theri in #227:
- "Notification of Excessive Retransmission" is made a Selection Property
- There's now an "Excessive Retransmission" Event (just like the one for Soft Errors)
- The preference to receive Soft Errors is also made a Selection Property
=> Split Notification of Excessive Retransmission, and make the preference to receive Soft Errors a Selection Property

draft-ietf-taps-interface.md
This PR provides usage examples of our abstract interface, to address #247.
The examples show how an application might use Listen(), Initiate(), and Rendezvous(), send a Message, and receive a Message.
There is some redundancy between these examples, and I introduces some subtle differences to make them plausible, e.g., the "server" provides its identity, and the "client" verifies the other endpoint's identity using a trust callback.
Overall the section became rather long. Should we instead just stick to one example, e.g., Initiate()? (Or Rendezvous() because it covers the most aspects? Or Initiate() but with all the aspects from Rendezvous()?)
Otherwise I'm particularly interested in feedback on the Rendezvous() example -- I think it's correct wrt the draft, but is there a "more …
=> API usage examples

draft-ietf-taps-interface.md
This implements the consensus on Transport Property Names from the Januar '19 Interim and the mailing list discussion about an IANA Registry for Property names.
This also closes #243.
=> Add Transport Property Names to the API

draft-ietf-taps-arch.md, draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Alternate proposal to address #45 (old PR was "Add CacheContext to architecture and API", #244)
- Define explicit Connection Groups as a way to define caching boundaries
- Update TLS 1.3 references to RFC 8446
=> Caching Boundaries using Connection Groups

draft-ietf-taps-interface.md
This PR is based on the presentation given at IETF 104 and the received feedback regarding Framers. This enhances and clarifies the API text around how framers are set up and used.
=> Add details to the Framer Interface

draft-ietf-taps-interface.md
... and some nits (capitalization, ..)
#314: 0-rtt establishment: fixed default as requested by @gorryfair and incorporated text fix suggestion
#315: last missing update to hopefully close this issue: adjusted the wording of checksum related selection properties
#316: fixed some text details regarding how transport properties are to be specified, based on a converged discussion.
#331: wrote some defaults for parameters in section 9.1
=> Various minor issues - closes #314, #315 #316 and #331

draft-ietf-taps-impl.md
Starting to address #128 
This is an early review, to check if we like the structure. I'd also like help filling out the SCTP section!
=> Make protocol-specific mappings in TAPS Implementation more rigorous

draft-ietf-taps-interface.md
=> Add Transport Property Profiles

draft-ietf-taps-interface.md
This implements what we discussed on #343
=> Allow setting new connection limits for inbound connections

draft-ietf-taps-arch.md
Based on discussion with @mirjak, rearrange things to put a proper document overview in the intro, and split out the API Model discussion into its own section outside of the introduction.
=> Architecture: Make overview section an actual overview

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Closes #337 (SCTP mapping)
This uses a new approach for such text for TCP, UDP and SCTP.
Also: updates appendix D of interface.
=> Implementation: mapping back to RFC 8303

draft-ietf-taps-impl.md
https://github.com/ietf-tapswg/api-drafts/issues/150
After some discussion with Max and Theresa, we believe the interface draft does not need any changes.  This adds a UDP Multicast Receive protocol-specific section to outline the specific considerations for a UDP multicast receive connection.
=> udp multicast receive (#150)

draft-ietf-taps-arch.md, draft-ietf-taps-impl.md
This is necessary to allow CircleCI builds, which have changed to use XMLv3 in the workflow, to continue: XMLv3 requires a <date year> attribute in all refs, where v2 did not.
=> add dates to references, and clean up spurious ones

draft-ietf-taps-arch.md
=> Move Transport Properties text and close #373

draft-ietf-taps-interface.md
This also addresses two inline [EDITOR's NOTE] items.
One was about the per-message override capacity profile being inconsistent with the other one; this was solved by removing details, such that the other one defines the possible choices.
Another was about selection vs. connection properties, with broken text. There was no need to add the references as the editor's note says, I thought.
=> minset appendix update: section references

draft-ietf-taps-arch.md
From the email:
```
In Section 2
/The Socket API/
The text uses /sockets/, but previously the text in 2.1 talks about the Socket API. 
I didn’t see a problem here while we were working on the spec, but I think it world be better is section 2 explicating introduced the word /sockets/ and defined the Socket API as a definition of the sockets method. At least /sockets/ needs to be explained before it is used in Sections 2.1 2.2, 2.3, etc.
---
In Section 3.2
/handover or failover for a Connection/
- should this use a lower case letter ‘c’ for connection. This seems to be before the document defines a specific meaning for a TAPS Connection.
---
In Title of Figure 4: 
Title: /The lifetime of a connection/
- I think this does warrant a capital letter ‘C’ for connection? or alternatively a …
```
=> Address on Gorry's WGLC comments

draft-ietf-taps-interface.md
When reading the API draft, I noticed that in some places it was still using the outdated term "Protocol Properties" where it actually means Connection Properties or Message Properties.
I replaced the terms in this PR.
We do still define "Specific Protocol Properties", so I kept these.
=> API draft: Replace "Protocol Properties" with updated terms

draft-ietf-taps-interface.md
Add a reference to MPS in DPLPMTUD for the Message Size Before Fragmentation property.
=> Add a reference to DPLPMTUD for Message Size before fragmentation

draft-ietf-taps-interface.md
The term Protocol Specific Properties is not well introduced. In the Arch doc we have a section about "Specialized Features" and I not added a reference and rephrased the sentence respectively. Do we need to say more than that?
=> Protocol Specific Properties are not well defined

draft-ietf-taps-interface.md
I'm not quite sure what I meant by "Only full coverage is guaranteed, any other requests are advisory". I assume we mean that even if a partial checksum is requested you get full coverage because requesting partial coverage and getting no checksum doesn't seem right...?
=> checksum default and clarification

draft-ietf-taps-arch.md
Fixed some upper-case/lower-case issues where I think I know the right answer.
Also, a few sentences seemed incomplete or like they could be clearer.
Moreover, endpoint resolution occured "in response to the Initiate call", but "during the Rendezvous call" - I think "in response to" is better, as "during" sounds like it's a blocking call. Alternatively, this could be "after [the call]".
=> Arch: Some consistency and clarity fixes

draft-ietf-taps-arch.md
Following #389, Section 4.2.3 of the Architecture document now says that fallback between different security protocol versions might be allowed.
The Security Considerations section was out of sync. This PR fixes that.
=> Arch: Adjust Security Considerations to new Section 4.2.3

draft-ietf-taps-interface.md
- Example code updates: this is to try to avoid people stumbling over, e.g., "send" being part of the "main code". I believe it's a little cleaner with these added comments.
- Lifetime Message property: mentioned -1 as a special value for infinite, else it's a bit odd to only use "infinite" for an integer
- very minor text fix about corruption protection length Message property
=> Some small proposed fixes

draft-ietf-taps-interface.md
It looks like we should use normative language here. We could also use the keywords of the IANA protocol number registry to indicate reserved namespaces for IETF protocols (that can not be used in the vendor or implementation specific namespaces anyway). See https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
=> Normative language for property namespace

draft-ietf-taps-interface.md
Make clearer what "Priority is not entangled" means, following #461.
Also added a note that Clone() may result in on-the-wire signaling.
=> Clarify Clone and Priority, closes #461

draft-ietf-taps-interface.md
I think the intro currently doesn't fit well the content of the document as any motivation for this work should be in the Arch doc. If we want to retain the text that I deleted we can maybe add it to the Intro or background section in the Arch doc...?
Note that the second paragraph I've added is stolen from the intro of the Arch doc.
=> Proposed alternative intro text for API doc

draft-ietf-taps-interface.md
The section on Message Contexts is really misplaced at the moment. I suggest to have it just before the section on Message Properties because it actually used there (also in the example).
=> Moving section on Message Contexts

draft-ietf-taps-interface.md
Fixed text in the API draft to allow reusing Preconnections as discussed in #222. 
However, changes to the Preconnection MUST NOT have any effect on the Connections or Listeners created beforehand - I think normative language is useful here to really highlight this possible pitfall. I omitted any note on deep copy as that's just a way to implement this.
=> Allow reusing Preconnections, fixes #222

draft-ietf-taps-interface.md
In the "Specifying Endpoints" section, added a reference to the Selection Property that does a similar thing but with more fine-grained control.
It wasn't clear to me what is the best place to add this, so I put it right below the first example of specifying an interface name for the Local Endpoint to say that you can also do it differently. If you have better suggestions, please let me know.
To the ListenError and RendezvousError, I added text mentioning the "reconcile Endpoints and Properties" pitfall. I think this is probably more general, i.e., there might be more sources of errors than just local interface, so I kept it generic.
=> Local Endpoint vs. Selection Property, closes #410

draft-ietf-taps-interface.md
Comma in the first section was wrong but better to rephrase anyway...
=> editorial fix

draft-ietf-taps-interface.md
Btw why do we have (only) properties for the TCP UTO?
=> Restructure TCP UTO section

draft-ietf-taps-interface.md
Btw. does this cover all events? There is an issue where I also ask if we e.g. need an event that sending failed due to lifetime expiry. is there a way to double-check if we considered all needed events? Should we also mention ConnectionErrors here? Maybe we anyway need to say more about error?
=> New upper section for connection events

draft-ietf-taps-interface.md
Following the discussion in #464, explain why TCP UTO is included as a Protocol-Specific Property, while other properties are not.
Also, some minor consistency fixes.
=> Justify why TCP UTO is included

draft-ietf-taps-interface.md
Added defaults for interface and PvD following #435.
Also, I caught one leftover "recommended default".
=> Default for interface and PvD is no preference, fixes #435

draft-ietf-taps-interface.md
Tentatively answering my own questions in #408:
> The RendezvousError (Section 6.3) includes a messageContext (which is even required), but neither the InitiateError nor the ListenError include one. Why? Should this messageContext at least be optional?
Removed the messageContext here because the RendezvousError does not necessarily relate to a specific sent Message. If it does, the "reason" parameter can point to that message and/or a messageContext.
> In Section 7.3, it says "The Sent Event contains an implementation-specific reference to the Message to which it applies." - Is this in addition to the messageContext? If yes, why do we need both?
The beginning of Section 7 actually already said that this IS the messageContext. I removed the word "implementation-specific" because to me this …
=> Minor fixes with messageContexts, fixes #408

draft-ietf-taps-interface.md
Took a stab at normative language for the rules to process Selection Properties, as discussed in #429.
As far as I remember, we always said that outcomes have to be deterministic/consistent, so I made everything that matters a MUST.
I guess our example illustrates that even given the same Selection Properties, the outcome might change depending on the situation, e.g., your path might still be Wifi but it might or might not support your preferred protocol.
So, does this really have to be all MUST, or is there a SHOULD in there? Discuss. :)
Also, if anyone can name a good reason why the outcome has to be deterministic, please suggest text - maybe something like "avoid surprises for the application", but this didn't really sound right, so I left it out for now.
=> Add justification and normative language, fixes #429

draft-ietf-taps-interface.md
This ended up in more text that I thought. I'm not certain if we need all of it. Further I'm unsure about the concrete wording in many cases, so any comments are more than welcome!
=> First attempt to write some privacy considerations

draft-ietf-taps-interface.md
Following the suggestion in #436, made Local Address Preference a Set(Preference, Enumeration), so an application can now also Require or Prohibit stable addresses.
Added a sentence warning that, e.g., preferring stable AND temporary addresses does not make sense - but there are less obvious ways to produce a conflicting set of Selection Properties, too, and we know how to deal with them.
=> Refactor Local Address Preference, fixes #436

draft-ietf-taps-interface.md
#454: added a statement about data arriving before Receive is issued;
#450: removed the confusing sentence;
#494: carried out replacements suggested by @gorryfair
=> API receive semantics and DSCP text fixes; closes minor issues #454 #450 #494

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
In the [February 2020 interim](http://etherpad.tools.ietf.org:9000/p/notes-ietf-interim-2020-feb), people found the normative language in #496 too restrictive and agreed with the original suggestion in #429.
Therefore, this PR moves the selection algorithm text to the implementation draft and removes some normative language in the interface draft.
We still want to provide consistency to applications when possible, so there's a sentence in the implementation draft on this now as well.
=> Move algorithm text to Implementation draft, make Interface draft more flexible

draft-ietf-taps-arch.md
Addresses #418.
Removes most of the normative language in arch, which wasn't strictly necessary. What's left is the careful text around security protocols being raced, etc, which I believe is required.
=> Clean up unnecessary normative language in arch

draft-ietf-taps-interface.md
Here's the list of comments that this resolves, along with answers on how I did it:
2. Terminology and Notation
* "The method for
dispatching and handling Events is an implementation detail, with the
caveat that the interface for receiving Messages must require the
application to invoke the Connection.Receive() Action once per
Message to be received (see Section 8)."
This isn't true if ReceivedPartial events are triggered, right? Also, it's not really clear that any of this discussion belongs in a section titled "Terminology and Notation". This issue is alluded to later in the doc, and probably mostly belongs in the implementation doc.
MW: Agreed, removed this sentence.
3. Interface Design Principles
* What does "long-term caching of cryptographic identities" mean? The implication seems …
=> Addressing some of Kyle Rose's comments

draft-ietf-taps-impl.md
You cannot have references in the abstract. Initially I only wanted to remove that reference but then I also took the opportunity to rewrite the abstract a bit to not only talk about the architecture but an TAPS _system_ and the interface that this guide helps with its implementation.
=> No reference in abstract

draft-ietf-taps-interface.md
... such as: using CamlCase instead of dashes for property names.
Also: fixes consistency problem of apostrophs / quotation marks  (` vs `` vs " )
=> Closes #515.  + addresses a few more of the easy things from Kyle's review.

draft-ietf-taps-interface.md
... as suggested by @tfpauly.
Closes #448.
=> Partial send: remove sentence about re-using the same object

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
=> API: state "Ephemeral port used when no Local Endpoint specified"

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Closes #522.
This replaces a previous PR for the same issue, which I deleted: in this PR, I just added the definition of idempotency from RFC 7231, but this isn't good enough. We can't guarantee that these Messages would only *consecutively* arrive as duplicates, so these should be called "safely replayable" instead. See the discussion in #522.
=> Replace "idempotent" with "safely replayable" everywhere

draft-ietf-taps-interface.md
Closes #528.
I chose boolean, because, when querying, it only matters whether a Selection Property was chosen or not (I believe).
=> Define a new type to use when selection properties are queried

draft-ietf-taps-interface.md
Fixing three oddities in the abstract, issue #567
=> Fix three oddities in the abstract of draft-ietf-taps-interface

draft-ietf-taps-interface.md
* Clarify how the IANA protocol numbers registry keywords (largely upper-case) textually relate to Transport Property Names.
* Refine some of the surrounding text.
=> Clarify Transport Property name text - resolves #568

draft-ietf-taps-interface.md
I was about to change this must to MUST, however, MUST and "sensible" doesn't work well together, so I proposed this recommendation instead.
=> "must provide sensible defaults"

draft-ietf-taps-interface.md
This doesn't change the idea of translating keywords from the IANA protocol numbers registry to lower-case; it just removes the requirement for all Transport Property Names to be lower-case.
Why? Right now, they're camlCase, and I guess that reads better than changing them all into hardtoreadstrings or using-hyphens-everywhere ...
=> Remove the "lower-case" requirement for transport property names

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Closes #540.
I also added a link to NEATPy in the overview of implementations, and inserted a missing word in interface (a missing "without", must have been a nit)
=> Align message properties between impl and API

draft-ietf-taps-interface.md
No need to have a different type of Event for initiate, listen and rendezvous. Closes #510.
=> Unify establishment errors

draft-ietf-taps-interface.md
* Updates PR #596 to remove reference to lower-case in namespaces
corresponding to IANA protocol names.
* Express that strict adherence to the doc's naming convention is not
required, but that symbols in different languages should be
visually similar.
=> Clarify naming convention variance

draft-ietf-taps-interface.md
If I understand correctly, we're staying with the current master.
Therefore, here's my PR to fix #609 - I think we always want to override, and if we override, calling it Set() makes this clearer than Add().
For Security Parameters, perhaps it should be possible to add multiple identities, ciphersuites, etc.
But that's out of scope for this PR.
=> Transport Properties and Security Parameters: Set() not Add()

draft-ietf-taps-impl.md
Removed phrasing that implies 0-RTT data is just one packet and added a reference to the Maximum Message Size with Connection Establishment property.
Added a sentence on how/when an implementation can set this property.
=> Clarify that amount of 0-RTT data varies by protocol, closes #580

draft-ietf-taps-arch.md
This is a set of proposed editorial changes, following a complete pass through the ID. It also offers a one-word fix for Issue #634
This is mainly minor editorial work - except for a proposal to move the definition of "endpoint" upwards, because I found discussion of endpoints in preconception relied upon the endpoint concept. I also think we should have made our meaning of endpoint more explicit, because it is a term that we use a lot.
I also suggested we replaced the word "options" within the selection properties para, because a long time ago I think we changed the use of that word in this context  to "properties".
=> Editorial draft-ietf-taps-arch.md

draft-ietf-taps-interface.md
Closes #625, #627, #629. Partially addresses #631.
=> Editorial fixes to API draft.

draft-ietf-taps-interface.md
Closes #660, #663, #665, #670, #671. Partially addresses #655.
A few comments:
#655: Kyle's comment addressed ("Connection Properties can be set on Preconnections" fixed to "Connection Properties can be set on Preconnections and Connections")
#660: I don't think the sentence explaining what an application could do upon an establisment error is necessary. I removed it, and now the text should be clearer.
#663: All Connection Properties but "Priority (Connection)" are entangled. This is now clearly stated, not mentioned as an example.
#665: Great catch. I now replaced this with an example that talks about ordering (clearly, requiring ordering from UDP will have to fail).
#670: Reworded all the bits you point out, hopefully it's all clearer now.
#671: first, there was a broken sentence, …
=> Various edits, addressing Kyle's easier points.

draft-ietf-taps-interface.md
=> Add a security consideration about partial messages

draft-ietf-taps-impl.md
=> Clarify "consumed" and "failed to send" timing.

draft-ietf-taps-interface.md
Clarify that the Connection returned by Clone will send a Ready Event or an InitiateError Event.
Closes #760.
=> Events upon Clone

draft-ietf-taps-impl.md
Closes #708.
This is a manual re-application of all the changes to -impl in PR #722.
(Other methods didn't easily work because the master has changed quite a bit during discussion of PR #722; at least I found no easy way).
=> SCTP stream mapping, closes #708. (manual re-application of PR #722)

draft-ietf-taps-interface.md
This fixes a wrong reference to the "no segmentation" property: in fact, the "request not to bundle messages" is SCTP's Nagle, and covered by the Capacity profile.
(I mentioned this mistake in #782).
=> Tiny minset fix

draft-ietf-taps-interface.md
Closes #774. Closes #788.
This changes the use of the term "entanglement" as discussed in #774, and moves some text around in this section for better clarity and less repetition. Also, addressing #788, it introduces a framer as an optional parameter to the Clone call.
=> Fixes around Clone and entanglement

draft-ietf-taps-interface.md
=> Ignore preservation of message boundaries for selection by default.

draft-ietf-taps-interface.md
This attempts to set "no segmentation" as the usual case, and this as a corner case - such as would be from a transport that segments at layer 4, but does not fragment at layer 3. This latter case is what is desired to send one message using a sequence of seprate IP packets.
=> Suggestion for no fragmentation

draft-ietf-taps-interface.md
Not requiring things to be unreliable, but allow no reliability guarentees.
and /throw/generate/
=> Not unreliable, but no reliability guarentees.

draft-ietf-taps-interface.md
Tries to clarify that a Connection is a logical connection, and doesn't necessarily require a connection oriented underlying transport protocol. 
Cross-reference to the descriptions of Preconnection and the connection establishment procedures.
=> Clarifications around Connections

draft-ietf-taps-interface.md
In response to #813 ... This moves the discussion of protocol instances into bullet 4, and the properties (mainly selection) into bullet 5. It does not intend to change any text, and is intended to avoid what appeared to be overlap.
=> Re-group managing  properties & protocol instances

draft-ietf-taps-arch.md
Be clear that the API is asynchronous (not the whole arch); and reword the read example to also be asynchronous.
=> ARCH Example completion of a read call

draft-ietf-taps-interface.md
As discussed at the last interim, but cleaning up the references to use the real property names too.
=> Minset: Fixing wrong statement about missing soft error, name cleanup

draft-ietf-taps-interface.md
This makes the following changes:
* Add `AddRemote()`, `RemoveRemote()`, `AddLocal()`, and `RemoveLocal()`
actions to existing connections
* Update the description of the `PathChanged()` event to note that it's
generated if the set of local endpoints available changes
* Update the peer-to-peer example to show how these can be used to support
Trickle ICE
Closes #961
Closes #911
Closes #865
=> Handle changes to connection endpoints

draft-ietf-taps-arch.md
This is the only place multicast considerations might fit in -arch. We don't discuss anycast at all, and I think it's largely orthogonal to transport (indeed, people seem to be running stateful/connection-oriented transports to anycast endpoints just fine in the Internet, even though it "doesn't work" :) )
=> mention multicast endpoints; addresses #885

draft-ietf-taps-interface.md
I think this reflects prior agreement, which for some reason just wasn't applied to the API draft yet.
=> Update author list as previously agreed

draft-ietf-taps-interface.md
=> Clarify framer-specific message properties

draft-ietf-taps-arch.md
This pull requests fixes two minor typos in draft-ietf-taps-arch.md that I noticed during detailed reading of the draft.
=> Fix two minor typos in architecture document

draft-ietf-taps-interface.md
An alternative would be to remove negative values from the definition of Integer and Numeric, because I think we have no single negative usage anywhere. Still ... to me, this PR seems cleaner (more forward-looking, as we might want to support negative values in some future update?)
=> A few nits; primarily adding "non-negative" in some places

draft-ietf-taps-interface.md
The guidance applies to any connectionless transport.
=> Update to resolve Datagram v Connectionless

draft-ietf-taps-arch.md
=> Address SECDIR review of -arch

draft-ietf-taps-impl.md
=> Remove unnecessary normative language in implementation

draft-ietf-taps-interface.md
Closes #1049.
I added text to ConnectionReceived about this. I didn't additionally explicitly state this in the text about clone to avoid complicating things - since similarly, the text describing Initiate() doesn't talk about ConnectionReceived.
=> Clone causes a ConnectionReceived event.

draft-ietf-taps-interface.md
This is a remake of #1021 as @GrumpyOldTroll suggested.
It moves the WithIPvXMulticastGroup for receiving to the LocalEndpoint and adds the ASM/SSM distinguisher.
It does not add TTL support.
=> Sketch alternative multicast model – #1021 reloaded

draft-ietf-taps-impl.md
This PR covers steps 1 and 2 in #608. When aligning the error events for UDP multicast I also noticed that the text for UDP was not correct as soft errors do not generate ConnectionError events so also attempted to fix this.
=> Terminology alignment and consistent coverage of actions and events

draft-ietf-taps-impl.md
Initially I thought the description for UDP-Lite was incomplete, but mapping back to the details of the API draft I realized it was incorrect. UDP-Lite supports the msgChecksumLen and recvChecksumLen properties. 
The API for theses primitives is a bit messy. As specified I think it means the following:
- UDP can use them to set full coverage or no checksum using the special value of 0.
- UDP-Lite can use them to set full coverage or a partial coverage.
- Setting the checksum to only cover the header, although supported by UDP-Lite, will not be possible as 0 is a special value.
The special value of 0 can not be used by UDP-Lite, but I left this detail out of the pull request as I thought it got very detailed. It can be added if you think it is needed.
=> Updates the description for UDP-Lite.

draft-ietf-taps-interface.md
Closes #1092. This implements the change I suggested in #1092, and it also replaces "Protocol Specific Properties" with "protocol-specific Properties".
=> Be more specific on namespace

draft-ietf-taps-interface.md
=> API: default value for "Timeout for keep alive packets".

draft-ietf-taps-interface.md
This is my attempt to address items 2, 3 and 4. My suggestion is not to do anything about item 1 (referencing -arch), because we already do this so often and IMO it won't improve the document to add yet another reference. See also the discussion in #1095.
Closes #1095.
=> Items 2, 3, 4 of #1095 (nits)

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Closes #1101.
We don't have "Protocol Properties" - two occurrences in -interface should really refer to "protocol-specific Properties", and two occurrences in -impl should really refer to properties.
=> Rename/remove "protocol properties"

draft-ietf-taps-interface.md
=> Normatively forbid multiple identifiers per endpoint.

draft-ietf-taps-interface.md
There was a mismatched "(". Not sure I am fixing it properly though.
=> Editorial Nit

draft-ietf-taps-arch.md
Add an Operations and Management Considerations section pointing out hooks for ops and management (and declaring specifications for them to be out of scope, because implementation dependent).
Add a new Coexistence subsection to make it explicit that we intend for this architecture to exist alongside / atop the Socket API.
=> Address OPSDIR management comment - fix #1153

draft-ietf-taps-interface.md
We already use MUST NOT for Init() and Listen(), so it's probably better to do the same for Rendezvous.
Closes #1146.
=> One change to normative, for consistency

draft-ietf-taps-impl.md
Pretty much following all suggestions in #1139. I only didn't add the sentence about "Effectively, the streams are an additional protocol layer on top of the transport..." because I don't think this contributes much.
=> handling muxed conns. Closes #1139.

draft-ietf-taps-arch.md, draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
Closes #1170 
- Makes "Message" generally capitalized, except when used in a phrase like "message boundaries"
- Makes "action", "event", and "object" lowercase
- Use "`" marks for events and actions to indicate "code voice"
=> Style for actions, events, objects, and messages

draft-ietf-taps-impl.md
introducing the class "handshake-less protocol" does not seem necessary to me, so I have only tried to make the text a bit more explicit to deal with the feedback.
=> Resolves #1140 Handling connectionless protocols

draft-ietf-taps-interface.md
...  to clarify that this is not only SCTP-specific.
Closes #1194.
=> Tiny wording change on schedulers

draft-ietf-taps-interface.md
=> Make Endpoints consistent with basic types 

draft-ietf-taps-arch.md
We need to be careful, if we say a host, ought we say a host or a multicast group?
=> Should remote endpoint include mcast group?

draft-ietf-taps-interface.md
Closes #1259 
Closes #1268 
Closes #1264
=> Editorial fixes + Namespaces: distinguish vendors from IETF protocols + rephrasing "RFC series"

draft-ietf-taps-interface.md
We provide UTO here as an example of something that is offered by a specific transport. It is true that QUIC also includes a UTO - but we don't have a QUIC spec yet, and anyway other protocols may also define transport-specific options.  I suggest this is sufficiently niche that the example prevails - when you tear doen a QUIC connection might be different to a TCP connection, because of differences in transport. I therefore propose some minor teaks and think we ought not to say about QUIC here.
Will close #1303 if merged
=> Make UTO more clearly a TCP example

draft-ietf-taps-interface.md
Closes #1348
This also removes the mention of "Corruption" in the msgReliable property description.
=> Clarify "later control" of checksum coverage

draft-ietf-taps-interface.md
Suggested to align with other IETF specs. Closes 1378 ifhen merged.
=> Change hi<->lo priority

draft-ietf-taps-interface.md
Closes #1283.
May become unnecessary though, depending on what we think of #1352.
=> Wording of receiver backpressure.

draft-ietf-taps-interface.md
Closes #1307
In a PR where some "should not" became "ought not", this was chosen to be "ought not", but I think Erik is right in #1307 about this one, SHOULD NOT seems better to me.
=> app SHOULD NOT assume that ignoring events is always safe

draft-ietf-taps-interface.md
Closes #1332
Closes #1333
Closes #1361
=> Protocol identifiers are strings, listed in the API doc., and shouldn't normally be used

draft-ietf-taps-interface.md
Closes #1310
*I* like it a little better with this change, but I remember that we had a real discussion about "Ignore", this term wasn't "just" picked - I believe @abrunstrom was a part of this discussion.
There are good reasons for either choice, I think. If you want a good reason for keeping "Ignore", look at one of the tables at the end of this PR: "congestionControl: none" and "preserveMsgBoundaries: none" can easily be taken to mean "no congestion control" and "no boundaries". Of course this could be solved by calling it "no preference" (but then it's two words, not one, and also "preference" is the name of the type itself).
I have no strong opinion here. Let's have a quick chat about this and decide.
=> Ignore => None

draft-ietf-taps-interface.md
alternative to #1402
closes #1338
=> Make Transport Property Names more strict (and case-insenstitive)

draft-ietf-taps-interface.md
I did another check of the minset appendix just to make sure all references and property names etc. are still correct (they are).
In doing so, I found it useful to add a sentence explaining the point of this appendix (it facilitates finding the right spec). I also added an anchor to have a more specific section reference for the Receive action.
=> Tiny minset appendix update

draft-ietf-taps-interface.md
Replace the over-specific definitions with racing compatible equivalents without mentioning racing.
Fixes #1339 
Fixes #1340
=> Clarify multiple Local/remote endpoints

draft-ietf-taps-interface.md
Closes #1331
Note: at the interim, we discussed that we could also point at Preconnection.Resolve() as a way to get interface names. I decided against this, however, due to the text that was added there by PR #947: "Note that the set of Local Endpoints returned by Resolve might or might not contain information about all possible local interfaces; it is valid only for a Rendezvous happening at the same time as the resolution. Care ought to be taken in using these values in any other context."
=> This seems to specifically warn against getting interface names for any other purpose with Resolve().
=> Where do interface names come from?

draft-ietf-taps-impl.md
This is supposed to fix
#1322 – IPv6 address representation and port number
#1324 – Change a few examples from IPv4/LTE to IPv6?
=> Make IPv4 and IPv6 port numbers consistent

draft-ietf-taps-interface.md
=> What about zero Integer or Numeric values?

draft-ietf-taps-impl.md
This addresses a point made in #1150
=> Not "values" for "Connectedness"

draft-ietf-taps-impl.md
=> Explain stacked layers of keep alive protocols

draft-ietf-taps-interface.md
Clarifies the limitations of using `Resolve()` on a `Preconnection` and makes it clear that it can be used to find local interfaces. Removes the need for a non-standard interface for this when we have a standard one.
Closes #1331
=> Use Resolve() to find local interfaces

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
We got a comment for one such occurrence, but it makes sense to improve section references in the same way everywhere.
=> Section references to RFCs and I-Ds inside curly brackets

draft-ietf-taps-impl.md, draft-ietf-taps-interface.md
#1460 raises three points:
1) "I'm not sure that the model really expands from netflows to IP flows (or TOR)
in the future."  => not addressed here.
2) re-using the same credentials with different protocols/auth mechanisms. => I think the fourth paragraph of the -arch Security Considerations speaks to this; instead of repeating it, I thought it would be better to point at this document (similar to how the implementation draft does it), as its security considerations should apply to all of the API draft anyway.
3) not using an FQDN punts a security risk mostly to the application: I more or less copied the wording about the no-FQDN security risk from section 6.1, it seems fair to repeat this here as a warning.
=> Security Considerations: a first stab at #1460
